/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mn.shand.v201807;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Ganbat Bayarbaatar <ganbat96@gmail.com>
 */
public class AlertPanel extends javax.swing.JPanel {
    private AlertTableModel tableModel = new AlertTableModel();

    /**
     * Creates new form AlertPanel
     */
    public AlertPanel() {
        initComponents();
    }

    public void refresh(List<Alert.Result> result) {
        tableModel.values = result;
        logTable.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        logTable.setModel(tableModel);
        jScrollPane5.setViewportView(logTable);

        add(jScrollPane5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable logTable;
    // End of variables declaration//GEN-END:variables

    public static class AlertTableModel extends AbstractTableModel {
        private List<Alert.Result> values = new ArrayList<>();

        public AlertTableModel() {
        }

        @Override
        public int getRowCount() {
            return values.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public String getColumnName(int col) {
            switch (col) {
                case 0 : return "Төхөөрөмж";
                case 1 : return "Үзүүлэлт";
                case 2 : return "Одоогийн утга";
                case 3 : return "Анхааруулга өгөх нөхцөл";
            }

            return "col" + col;
        }

        @Override
        public Class getColumnClass(int c) {
            return String.class;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Alert.Result data = values.get(rowIndex);
            switch (columnIndex) {
                case 0 : return getName(data.getCode());
                case 1 : return getType(data.getItem().getType(), data.isSecond());
                case 2 : return data.getValue();
                case 3 : return data.getItem().getOperator() + " " + data.getItem().getValue();
            }

            return null;
        }


        private String getName(String code) {
            switch(code) {
                case "cc" : return "Худаг 3";
                case "bb" : return "Худаг 2";
                case "de" : return "Дэнж";
                case "gb" : return "Говь";
                case "zg" : return "Зээг";
                case "myng" : return "Мянгын сан";
            }

            return "";
        }

        private String getType(String code, boolean second) {
            switch(code) {
                case "temp" : return "Температур";
                case "rh" : return "Чийгшил";
                case "h"  : return "Төвшин";
                case "hh" : return second ? "Төвшин 2" : "Төвшин 1";
                case "pp" : return second ? "Даралт 2" : "Даралт 1";
                case "p"  : return "Даралт";
                case "dd" : return second ? "Доргио 2" : "Доргио 1";
                case "smoke" : return "Гал";
            }

            return "";
        }
    }
}
