/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mn.shand.v201807;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Ganbat Bayarbaatar <ganbat96@gmail.com>
 */
public class MeasurementPanel extends javax.swing.JPanel {

    private MeasureTableModel logTableModel = new MeasureTableModel();

    /**
     * Creates new form MeasurementPanel
     */
    public MeasurementPanel() {
        initComponents();

        jtDate.setText(LocalDate.now().format(DateTimeFormatter.ISO_DATE));

        jChkByDateActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jtRows = new javax.swing.JTextField();
        logSearchBtn = new javax.swing.JButton();
        jtDate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jChkByDate = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        logTable.setModel(logTableModel);
        jScrollPane5.setViewportView(logTable);

        add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jLabel21.setText("Шүүх мөрийн тоо");

        jtRows.setText("100");

        logSearchBtn.setText("Шүүх");
        logSearchBtn.setToolTipText("");
        logSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logSearchBtnActionPerformed(evt);
            }
        });

        jtDate.setText("jTextField1");

        jLabel22.setText("Шүүх огноо");

        jChkByDate.setText("Огноогоор шүүх");
        jChkByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkByDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkByDate)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtRows)
                            .addComponent(jtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(logSearchBtn)))
                .addContainerGap(965, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jChkByDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logSearchBtn)
                .addGap(26, 26, 26))
        );

        add(jPanel15, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void logSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logSearchBtnActionPerformed
        List<Map<String, String>> logs = null;
        if (jChkByDate.isSelected()) {
            if (jtDate.getText() != null) {
                logs = MeasureLog.search(jtDate.getText());
            }
        } else {
            int lineCount = Integer.parseInt(jtRows.getText());
            if (lineCount > 0) {
                logs = MeasureLog.tail(lineCount);
            }
        }

        logTableModel.values.clear();
        logTableModel.values.addAll(logs);

        logTable.updateUI();
    }//GEN-LAST:event_logSearchBtnActionPerformed

    private void jChkByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkByDateActionPerformed
        jtRows.setEnabled(!jChkByDate.isSelected());
        jtDate.setEnabled( jChkByDate.isSelected());
    }//GEN-LAST:event_jChkByDateActionPerformed

    public static class MeasureTableModel extends AbstractTableModel {
        private List<Map<String, String>> values = new ArrayList<>();

        public MeasureTableModel() {
        }

        @Override
        public int getRowCount() {
            return values.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public String getColumnName(int col) {
            switch (col) {
                case 0 : return "Огноо";
                case 1 : return "Зээг";
                case 2 : return "Говь";
                case 3 : return "Дэнж";
                case 4 : return "Мянга 1";
                case 5 : return "Мянга 2";
            }

            return "col" + col;
        }

        @Override
        public Class getColumnClass(int c) {
            return String.class;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Map<String, String> data = values.get(rowIndex);
            switch (columnIndex) {
                case 0 : return data.get("date");
                case 1 : return data.get("zg0");
                case 2 : return data.get("gb0");
                case 3 : return data.get("de0");
                case 4 : return data.get("myng1");
                case 5 : return data.get("myng2");
            }

            return null;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jChkByDate;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jtDate;
    private javax.swing.JTextField jtRows;
    private javax.swing.JButton logSearchBtn;
    private javax.swing.JTable logTable;
    // End of variables declaration//GEN-END:variables
}
